# Copyright (c) 2026 PaddlePaddle Authors. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Flash Attention v4 unified public interface.

Exposes the framework-specific backend through a single stable import path:

    from flash_mask.interface import flash_attn_func, flash_attn_varlen_func

The backend is fixed at **install time** via the ``FLASH_ATTN_BACKEND``
environment variable passed to ``pip install`` / ``setup.py``:

    FLASH_ATTN_BACKEND=paddle pip install -e . --no-build-isolation   # default
    FLASH_ATTN_BACKEND=torch  pip install -e . --no-build-isolation

The chosen value is baked into ``flash_mask/_backend.py`` by ``setup.py``.
No environment variable is needed (or checked) at runtime.
"""

import importlib

__all__ = [
    "flash_attn_func",
    "flash_attn_varlen_func",
    "flash_attn_combine",
    "flash_attention",
    "flashmask_attention",
]

_BACKENDS = {
    "paddle": "flash_mask.flash_attn_v4.paddle.interface",
    "torch":  "flash_mask.flash_attn_v4.torch.interface",
}

# ---------------------------------------------------------------------------
# Resolve backend name from compile-time _backend.py (generated by setup.py).
# Falls back to 'paddle' (matching setup.py default) if _backend.py is absent
# (e.g. running directly from a source checkout without pip install).
# ---------------------------------------------------------------------------
try:
    from flash_mask._backend import BACKEND as _backend_name
except ImportError:
    _backend_name = 'paddle'

if _backend_name not in _BACKENDS:
    raise ValueError(
        f"Unknown backend {_backend_name!r}, "
        f"expected one of {sorted(_BACKENDS)}"
    )

try:
    _mod = importlib.import_module(_BACKENDS[_backend_name])
except ImportError as e:
    raise ImportError(
        f"Backend {_backend_name!r} is not available. "
        f"Re-install with FLASH_ATTN_BACKEND={_backend_name} to confirm, "
        f"or switch backend via FLASH_ATTN_BACKEND at install time."
    ) from e

flash_attn_func        = _mod.flash_attn_func
flash_attn_varlen_func = _mod.flash_attn_varlen_func
flash_attn_combine     = _mod.flash_attn_combine

# ---------------------------------------------------------------------------
# Paddle-only high-level interfaces — sourced from flash_mask.cute.interface.
# These are not dispatched through the backend mechanism (no torch equivalent).
# Only imported when paddle backend is active.
# ---------------------------------------------------------------------------
if _backend_name == 'paddle':
    try:
        from flash_mask.cute.interface import flash_attention, flashmask_attention
    except ImportError:
        pass
